jobs:
  build:
    environment: debug
    name: JDK ${{ matrix.java-version }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      id: setup-ffmpeg
      name: Set up FFmpeg
      uses: FedericoCarboni/setup-ffmpeg@v3
      with:
        ffmpeg-version: release
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: temurin
        java-version: ${{ matrix.java-version }}
    - continue-on-error: true
      name: Compile with Maven
      run: mvn --batch-mode --update-snapshots compile
    - continue-on-error: true
      name: Test with Maven, Package and Verify with Maven
      run: mvn --batch-mode --update-snapshots verify -Dgpg.skip
    - continue-on-error: true
      name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@v4
    strategy:
      matrix:
        java-version:
        - 8
        - 11
        - 17
        - 21
name: Java CI with Maven
on:
  repository_dispatch:
    types: trigger-ga___maven.yml
